exclude: '^docs/conf.py|^tests/data/'

ci:
  autoupdate_schedule: monthly

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
    args: ['--unsafe']
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=no']
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    additional_dependencies:
      - flake8-quotes
      # - flake8-comprehensions
      - flake8-builtins
      # - flake8-eradicate
      - pep8-naming
      - flake8-pytest
      - flake8-docstrings
      - flake8-rst-docstrings
      - flake8-rst
#      - darglint
      - flake8-copyright

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
    - id: rst-backticks
    - id: rst-directive-colons
    - id: rst-inline-touching-normal
- repo: https://github.com/asottile/pyupgrade
  rev: v3.8.0
  hooks:
  -   id: pyupgrade
      args: [--py38-plus]
- repo: https://github.com/commitizen-tools/commitizen
  rev: 3.5.2
  hooks:
    - id: commitizen
      stages: [commit-msg]
