language: python
virtualenv:
  system_site_packages: false

os: linux
python:
  - '3.6'
  - '3.7'
  - '3.8'

jobs:
  include:
    - python: 3.7
      env: TOXENV=lint

install:
  - pip install -U pip tox-travis coverage codecov
script:
  - tox
after_success:
  - codecov
cache:
  pip: true
  directories:
    - $HOME/miniconda
