"""
Integration test for day 2023_210 comparing C-code outputs to alanmode functions.

Some tests in this module only run when on enterprise, where the raw spectra
are available. When not on enterprise, we short-circuit those tests by symlinking to the
legacy averaged spectra.

Legacy C code outputs are in `tests/data/alanmode/edges3-2023-210-alan/`.
S11 raw inputs are in `tests/data/alanmode/edges3-2023-210-raw/` (spectra aren't kept
there because they are too big).

Legacy C code outputs are generated by the the code in
https://github.com/edges-collab/alans-pipeline. Specifically, from top-level, run:

```bash
make
cd scripts/edges3
./docal_edges3_2023_210
cd ../..
cp results/edges3-2023-210/* <this_repo>/tests/data/alanmode/edges3-2023-210-alan/
```

These tests are very similar to the 2022_316 tests, but have some differences
(beyond just the datafiles used):

    - The assumed temperatures are different
    - The fstart/fstop are different than wfstart/wfstop in the calibration function
      (in 2022_316 the fstart/fstop is only specified on the acqplot7amoon step, while
      the fstart/fstop in edges() is equivalent to wfstart/wfstop).

Also, this test module gives us the chance to test the actual set of observations being
used for EDGES-3 first release.
"""

from pathlib import Path

import numpy as np
import pytest
from astropy import units as un
from astropy.table import QTable
from pygsdata import GSData

from edges import alanmode as am
from edges.cal import Calibrator

DATA_PATH = Path(__file__).resolve().parent.parent / "data" / "alanmode"

LEGACY_DATA_PATH = DATA_PATH / "edges3-2023-210-alan"
RAW_SPECTRUM_DIR = Path("/data5/edges/data/EDGES3_data/MRO")

ACQPARAMS = am.ACQPlot7aMoonParams(
    fstart=48.0,
    fstop=198.0,
    smooth=8,
    tload=300,
    tcal=400,
    tstart=0,
    tstop=23,
    delaystart=0,
)

DEFPARAMS = am.Edges3CalobsParams(
    specyear=2023,
    specday=210,
    s11date="2023_210_03",
    datadir=RAW_SPECTRUM_DIR
    if RAW_SPECTRUM_DIR.exists()
    else DATA_PATH / "edges3-2023-210-raw",
    match_resistance=49.8,
    calkit_delays=33,
    lna_cable_length=4.26,
    lna_cable_loss=-91.5,
    lna_cable_dielectric=-1.24,
)

CALPARAMS = am.EdgesScriptParams(
    fstart=48.0,  # This is the same as ACQPlot7aMoon, but doesn't *need* to be,
    fstop=198.0,  # and affects the S11 modeling.
    wfstart=50.0,
    wfstop=190.0,
    Lh=-1,
    thot=395.19,
    tcold=300.87,
    tcab=298.96,
    cfit=7,
    wfit=7,
    nfit2=27,
    nfit3=10,
)


@pytest.fixture(scope="module")
def output_dir(tmp_path_factory) -> Path:
    return tmp_path_factory.mktemp("edges3_2023_210_outputs")


@pytest.fixture(scope="module")
def legacy_averaged_spectrum_paths() -> dict[str, Path]:
    return {
        amode_key: LEGACY_DATA_PATH / f"sp{legacy_key}.txt"
        for legacy_key, amode_key in am.LOADMAP.items()
    }


@pytest.fixture(scope="module")
def alanmode_averaged_spectra(
    output_dir: Path,
    legacy_averaged_spectrum_paths: dict[str, Path],
) -> dict[str, GSData]:

    avg_spectrum_files = {
        amode_key: output_dir / f"sp{legacy_key}.txt"
        for legacy_key, amode_key in am.LOADMAP.items()
    }

    if not RAW_SPECTRUM_DIR.exists():
        # We're not on enterprise where the full data products are kept, so we cannot
        # run the full spectrum averaging (data is too big to store in repo)
        # Therefore, we short-circuit and use the legacy averaged spectra directly.
        for k, pth in avg_spectrum_files.items():
            legacy_file = legacy_averaged_spectrum_paths[k]
            pth.symlink_to(legacy_file)

    else:
        # We're on enterprise, so let's also test running the spectrum averaging.
        specfiles = DEFPARAMS.get_spectrum_files()
        for load, files in specfiles.items():
            outfile = avg_spectrum_files[load]
            gsd = am.acqplot7amoon(files, params=ACQPARAMS)
            am.write_spec_txt_gsd(gsd, outfile)

    return {
        k: am.read_spec_txt(pth, telescope="edges3", name=k)
        for k, pth in avg_spectrum_files.items()
    }


@pytest.fixture(scope="module")
def legacy_averaged_spectra(
    legacy_averaged_spectrum_paths: dict[str, Path],
) -> dict[str, GSData]:
    return {
        load: am.read_spec_txt(pth, telescope="edges3", name=load)
        for load, pth in legacy_averaged_spectrum_paths.items()
    }


@pytest.fixture(scope="module")
def alanmode_raw_s11s() -> tuple[np.ndarray, dict[str, np.ndarray]]:
    s11freq, raws11s = DEFPARAMS.get_raw_s11s()
    return s11freq, raws11s


@pytest.fixture(scope="module")
def _alanmode_calibration(
    legacy_averaged_spectra: dict[str, GSData],
    alanmode_raw_s11s: tuple[np.ndarray, dict[str, np.ndarray]],
):
    s11freq, raws11s = alanmode_raw_s11s

    # Note that we use legacy averaged spectra (i.e. pre-averaged and stored as files)
    # here, rather than the spectra averaged by the `acqplot7amoon` function in this
    # test suite. Since we already test whether the averaging is correct, it makes sense
    # to test all other parts of the calibration using the legacy averaged spectra,
    # which is much faster and isolates their role.
    calobs, calibrator, _, _, hot_loss_model = am.edges(
        spcold=legacy_averaged_spectra["ambient"],
        sphot=legacy_averaged_spectra["hot_load"],
        spopen=legacy_averaged_spectra["open"],
        spshort=legacy_averaged_spectra["short"],
        s11freq=s11freq,
        s11cold=raws11s["ambient"],
        s11hot=raws11s["hot_load"],
        s11open=raws11s["open"],
        s11short=raws11s["short"],
        s11lna=raws11s["receiver_s11"],
        s11rig=raws11s.get("s11rig"),
        s12rig=raws11s.get("s12rig"),
        s22rig=raws11s.get("s22rig"),
        params=CALPARAMS,
        tcal=ACQPARAMS.tcal * un.K,
        tload=ACQPARAMS.tload * un.K,
    )
    return calobs, calibrator, hot_loss_model


@pytest.fixture(scope="module")
def alanmode_modelled_s11s(output_dir: Path, _alanmode_calibration) -> np.ndarray:
    calobs, _, hot_loss_model = _alanmode_calibration
    am.write_modelled_s11s(calobs, output_dir / "s11_modelled.txt", hot_loss_model)

    return am.read_modelled_s11s(output_dir / "s11_modelled.txt")


@pytest.fixture(scope="module")
def alanmode_specal(output_dir: Path, _alanmode_calibration) -> Calibrator:
    calibrator = _alanmode_calibration[1]
    am.write_specal(
        calibrator,
        output_dir / "specal.txt",
        t_load=ACQPARAMS.tload,
        t_load_ns=ACQPARAMS.tcal,
    )

    return am.read_specal(
        output_dir / "specal.txt",
        t_load=ACQPARAMS.tload,
        t_load_ns=ACQPARAMS.tcal,
    )


@pytest.fixture(scope="module")
def legacy_specal() -> Calibrator:
    return am.read_specal(
        LEGACY_DATA_PATH / "specal.txt",
        t_load=ACQPARAMS.tload,
        t_load_ns=ACQPARAMS.tcal,
    )


@pytest.fixture(scope="module")
def alanmode_calibrated_temps(
    output_dir: Path, _alanmode_calibration
) -> dict[str, np.ndarray]:
    calobs, calibrator, _ = _alanmode_calibration

    out = {}
    for loadname in am.LOADMAP.values():
        load = calobs.loads[loadname]
        freqs = load.freqs.to_value("MHz")
        uncal = load.averaged_q
        cal = calibrator.calibrate_load(load).value
        np.savetxt(
            output_dir / f"calibrated_{loadname}.txt",
            np.array([freqs, uncal, cal]).T,
            header="freq uncal cal",
        )
        out[loadname] = am.read_calibrated_temp(
            output_dir / f"calibrated_{loadname}.txt"
        )

    return out


@pytest.fixture(scope="module")
def legacy_calibrated_temps(output_dir: Path) -> dict[str, np.ndarray]:
    out = {}
    for load in am.LOADMAP.values():
        fname = output_dir / f"calibrated_{load}.txt"
        out[load] = am.read_calibrated_temp(fname)

    return out


@pytest.mark.parametrize("load", list(am.LOADMAP.values()))
def test_spectrum_averaging(
    alanmode_averaged_spectra: dict[str, GSData],
    legacy_averaged_spectra: dict[str, GSData],
    load: str,
):
    if not RAW_SPECTRUM_DIR.exists():
        pytest.skip("Raw spectrum data not available, cannot test spectrum averaging.")

    ours = alanmode_averaged_spectra[load]

    np.testing.assert_allclose(legacy_averaged_spectra[load].freqs, ours.freqs)
    np.testing.assert_allclose(
        legacy_averaged_spectra[load].data[20:-20], ours.data[20:-20], atol=1e-6
    )


@pytest.mark.parametrize("legacy_key", [*list(am.LOADMAP.keys()), "lna"])
def test_unmodelled_s11(alanmode_raw_s11s, legacy_key):
    amode_key = "receiver_s11" if legacy_key == "lna" else am.LOADMAP[legacy_key]

    alanfreq, alans11 = am.read_s11_csv(LEGACY_DATA_PATH / f"s11{legacy_key}.csv")
    ourfreq, ours11 = alanmode_raw_s11s
    ours11 = ours11[amode_key]

    mask = (alanfreq >= ourfreq.min()) & (alanfreq <= ourfreq.max())
    np.testing.assert_allclose(alanfreq[mask], ourfreq)
    np.testing.assert_allclose(alans11[mask].real, ours11.real, atol=1e-10)
    np.testing.assert_allclose(alans11[mask].imag, ours11.imag, atol=1e-10)


@pytest.fixture(scope="module")
def legacy_modelled_s11s() -> QTable:
    return am.read_modelled_s11s(LEGACY_DATA_PATH / "s11_modelled.txt")


def test_modelled_s11(
    alanmode_modelled_s11s: QTable,
    legacy_modelled_s11s: QTable,
):
    alanfreq = legacy_modelled_s11s["freqs"]
    ourfreq = alanmode_modelled_s11s["freqs"]

    # Even though the legacy code ends up using modelled S11s only in the range
    # WFSTART to WFSTOP, the modelled S11s are actually generated across the full range
    # FSTART-FSTOP and written that way, so we need to mask them to compare
    mask = (alanfreq >= ourfreq.min()) & (alanfreq <= ourfreq.max())

    for key in alanmode_modelled_s11s.colnames:
        print("Testing modelled S11 for", key)

        # Test that all values are good to 1e-5
        np.testing.assert_allclose(
            alanmode_modelled_s11s[key],
            legacy_modelled_s11s[key][mask],
            atol=2e-5,
            rtol=0,
        )

        # Value not near the edges should be even better, at 1e-6
        np.testing.assert_allclose(
            alanmode_modelled_s11s[key][50:-50],
            legacy_modelled_s11s[key][mask][50:-50],
            atol=2e-6,
            rtol=0,
        )


def test_specal(alanmode_specal: Calibrator, legacy_specal: Calibrator):
    np.testing.assert_allclose(legacy_specal.freqs, alanmode_specal.freqs)
    np.testing.assert_allclose(legacy_specal.Tsca, alanmode_specal.Tsca, rtol=3e-6)
    np.testing.assert_allclose(legacy_specal.Toff, alanmode_specal.Toff, atol=4e-5)
    np.testing.assert_allclose(legacy_specal.Tunc, alanmode_specal.Tunc, atol=1.1e-6)
    np.testing.assert_allclose(legacy_specal.Tcos, alanmode_specal.Tcos, atol=2e-5)
    np.testing.assert_allclose(legacy_specal.Tsin, alanmode_specal.Tsin, atol=2.2e-5)


@pytest.mark.parametrize("key", am.LOADMAP.values())
def test_calibrated_temps(
    alanmode_calibrated_temps: dict[str, np.ndarray],
    legacy_calibrated_temps: dict[str, np.ndarray],
    key: str,
):
    alan = legacy_calibrated_temps[key]
    ours = alanmode_calibrated_temps[key]

    np.testing.assert_allclose(ours["freq"], alan["freq"], atol=0, rtol=0)
    np.testing.assert_allclose(ours["uncal"], alan["uncal"], atol=1e-6, rtol=0)
    np.testing.assert_allclose(ours["cal"], alan["cal"], atol=5e-5, rtol=0)
