"""
Integration tests comparing EDGES-3 C-code outputs to alanmode functions.

Every test in this module runs for each of two calibration datasets:

* ``2022_316``: the original EDGES-3 test day.
* ``2023_210``: the set of observations used for the first EDGES-3 release.

Apart from the data files, the two datasets differ in:

* the assumed load temperatures;
* fstart/fstop in the calibration step. In 2022_316, fstart/fstop are only set
  for the acqplot7amoon step, and the fstart/fstop in edges() equal
  wfstart/wfstop. In 2023_210 they are different, which affects the S11 modelling.

Some tests in this module only run on enterprise, where the raw spectra are
available. Elsewhere, those tests are short-circuited by using the legacy averaged
spectra.

Legacy C-code outputs are in `tests/data/alanmode/edges3-<year>-<day>-alan/`.
S11 raw inputs are in `tests/data/alanmode/edges3-<year>-<day>-raw/` (spectra aren't
kept there because they are too big).

The legacy C-code outputs are generated by the code in
https://github.com/edges-collab/alans-pipeline. Specifically, from top-level, run:

```bash
make
cd scripts/edges3
./docal_edges3_<year>_<day>
cd ../..
cp results/edges3-<year>-<day>/* \
    <this_repo>/tests/data/alanmode/edges3-<year>-<day>-alan/
```
"""

from pathlib import Path

import attrs
import numpy as np
import pytest
from astropy import units as un
from astropy.table import QTable
from pygsdata import GSData

from edges import alanmode as am
from edges.alanmode.alanmode import _acqplot7amoon
from edges.cal import Calibrator
from edges.cal import sparams as sp
from edges.cal.calobs import CalibrationObservation

DATA_PATH = Path(__file__).resolve().parent.parent / "data" / "alanmode"
RAW_SPECTRUM_DIR = Path("/data5/edges/data/EDGES3_data/MRO")

# Names of the calibrated-temperature files written by the C code (edges3.c).
CALIBRATED_TEMP_FILE_KEYS = {
    "ambient": "ambient",
    "hot_load": "hot",
    "open": "open",
    "short": "short",
}


@attrs.define(frozen=True)
class Dataset:
    """Inputs and expected precision for one legacy EDGES-3 calibration."""

    name: str
    acqparams: am.ACQPlot7aMoonParams
    defparams: am.Edges3CalobsParams
    calparams: am.EdgesScriptParams
    calibrated_temp_atol: dict[str, float]

    @property
    def legacy_data_path(self) -> Path:
        return DATA_PATH / f"edges3-{self.name.replace('_', '-')}-alan"


def _datadir(name: str) -> Path:
    if RAW_SPECTRUM_DIR.exists():
        return RAW_SPECTRUM_DIR
    return DATA_PATH / f"edges3-{name.replace('_', '-')}-raw"


_ACQPARAMS = am.ACQPlot7aMoonParams(
    fstart=48.0,
    fstop=198.0,
    smooth=8,
    tload=300,
    tcal=400,
    tstart=0,
    tstop=23,
    delaystart=0,
)

# Tolerances (in K) for the comparison of calibrated temperatures with Alan's
# calibrated_<load>.txt files. Ambient and hot agree to better than 0.1 mK. The open
# and short agree less well (2022_316: up to 1.3-1.5 mK at the 50 MHz edge and
# ~0.5-0.7 mK elsewhere, RMS ~0.25 mK; 2023_210: up to 0.08 mK for the open and 0.22
# mK for the short). The reason is not understood (see issue #311 and
# test_calibrated_temps_open_short_tight below), so they are tested at a realistic
# tolerance here that is still far below the noise in the calibration.
DATASETS = {
    "2022_316": Dataset(
        name="2022_316",
        acqparams=_ACQPARAMS,
        defparams=am.Edges3CalobsParams(
            specyear=2022,
            specday=316,
            s11date="2022_319_14",
            datadir=_datadir("2022_316"),
            match_resistance=49.8,
            calkit_delays=33,
            lna_cable_length=4.26,
            lna_cable_loss=-91.5,
            lna_cable_dielectric=-1.24,
        ),
        calparams=am.EdgesScriptParams(
            fstart=50.0,  # This is the same as wfstart, but doesn't need to be
            fstop=190.0,
            wfstart=50.0,
            wfstop=190.0,
            Lh=-1,
            tcold=306.5,
            thot=393.22,
            tcab=306.5,
            cfit=7,
            wfit=7,
            nfit2=27,
            nfit3=10,
        ),
        calibrated_temp_atol={
            "ambient": 5e-5,
            "hot_load": 1e-4,
            "open": 2e-3,
            "short": 2e-3,
        },
    ),
    "2023_210": Dataset(
        name="2023_210",
        acqparams=_ACQPARAMS,
        defparams=am.Edges3CalobsParams(
            specyear=2023,
            specday=210,
            s11date="2023_210_03",
            datadir=_datadir("2023_210"),
            match_resistance=49.8,
            calkit_delays=33,
            lna_cable_length=4.26,
            lna_cable_loss=-91.5,
            lna_cable_dielectric=-1.24,
        ),
        calparams=am.EdgesScriptParams(
            fstart=48.0,  # This is the same as ACQPlot7aMoon, but doesn't *need* to be,
            fstop=198.0,  # and affects the S11 modeling.
            wfstart=50.0,
            wfstop=190.0,
            Lh=-1,
            thot=395.19,
            tcold=300.87,
            tcab=298.96,
            cfit=7,
            wfit=7,
            nfit2=27,
            nfit3=10,
        ),
        calibrated_temp_atol={
            "ambient": 1e-5,
            "hot_load": 2e-5,
            "open": 2e-4,
            "short": 5e-4,
        },
    ),
}


@pytest.fixture(scope="module", params=list(DATASETS.values()), ids=list(DATASETS))
def dataset(request) -> Dataset:
    return request.param


@pytest.fixture(scope="module")
def output_dir(tmp_path_factory, dataset: Dataset) -> Path:
    return tmp_path_factory.mktemp(f"edges3_{dataset.name}_outputs")


@pytest.fixture(scope="module")
def legacy_averaged_spectrum_paths(dataset: Dataset) -> dict[str, Path]:
    return {
        amode_key: dataset.legacy_data_path / f"sp{legacy_key}.txt"
        for legacy_key, amode_key in am.LOADMAP.items()
    }


@pytest.fixture(scope="module")
def alanmode_averaged_spectra(
    dataset: Dataset,
    output_dir: Path,
    legacy_averaged_spectrum_paths: dict[str, Path],
) -> dict[str, GSData]:
    avg_spectrum_files = {
        amode_key: output_dir / f"sp{legacy_key}.txt"
        for legacy_key, amode_key in am.LOADMAP.items()
    }

    if not RAW_SPECTRUM_DIR.exists():
        # We're not on enterprise where the full data products are kept, so we cannot
        # run the full spectrum averaging (data is too big to store in repo)
        # Therefore, we short-circuit and use the legacy averaged spectra directly.
        for k, pth in avg_spectrum_files.items():
            legacy_file = legacy_averaged_spectrum_paths[k]
            pth.symlink_to(legacy_file)

    else:
        # We're on enterprise, so let's also test running the spectrum averaging.
        specfiles = dataset.defparams.get_spectrum_files()
        for load, files in specfiles.items():
            outfile = avg_spectrum_files[load]
            gsd, n = _acqplot7amoon(files, dataset.acqparams)
            am.write_spec_txt_gsd(gsd, outfile, n=n)

    return {
        k: am.read_spec_txt(pth, telescope="edges3", name=k)
        for k, pth in avg_spectrum_files.items()
    }


@pytest.fixture(scope="module")
def legacy_averaged_spectra(
    legacy_averaged_spectrum_paths: dict[str, Path],
) -> dict[str, GSData]:
    return {
        load: am.read_spec_txt(pth, telescope="edges3", name=load)
        for load, pth in legacy_averaged_spectrum_paths.items()
    }


@pytest.fixture(scope="module")
def alanmode_raw_s11s(dataset: Dataset) -> tuple[np.ndarray, dict[str, np.ndarray]]:
    s11freq, raws11s = dataset.defparams.get_raw_s11s()
    return s11freq, raws11s


@pytest.fixture(scope="module")
def _alanmode_calibration(
    dataset: Dataset,
    legacy_averaged_spectra: dict[str, GSData],
    alanmode_raw_s11s: tuple[np.ndarray, dict[str, np.ndarray]],
):
    s11freq, raws11s = alanmode_raw_s11s

    # Note that we use legacy averaged spectra (i.e. pre-averaged and stored as files)
    # here, rather than the spectra averaged by the `acqplot7amoon` function in this
    # test suite. Since we already test whether the averaging is correct, it makes sense
    # to test all other parts of the calibration using the legacy averaged spectra,
    # which is much faster and isolates their role.
    calobs, calibrator, _, _, hot_loss_model = am.edges(
        spcold=legacy_averaged_spectra["ambient"],
        sphot=legacy_averaged_spectra["hot_load"],
        spopen=legacy_averaged_spectra["open"],
        spshort=legacy_averaged_spectra["short"],
        s11freq=s11freq,
        s11cold=raws11s["ambient"],
        s11hot=raws11s["hot_load"],
        s11open=raws11s["open"],
        s11short=raws11s["short"],
        s11lna=raws11s["receiver_s11"],
        s11rig=raws11s.get("s11rig"),
        s12rig=raws11s.get("s12rig"),
        s22rig=raws11s.get("s22rig"),
        params=dataset.calparams,
        tcal=dataset.acqparams.tcal * un.K,
        tload=dataset.acqparams.tload * un.K,
    )
    return calobs, calibrator, hot_loss_model


@pytest.fixture(scope="module")
def alanmode_modelled_s11s(output_dir: Path, _alanmode_calibration) -> QTable:
    calobs, _, hot_loss_model = _alanmode_calibration
    am.write_modelled_s11s(calobs, output_dir / "s11_modelled.txt", hot_loss_model)

    return am.read_modelled_s11s(output_dir / "s11_modelled.txt")


@pytest.fixture(scope="module")
def alanmode_specal(
    dataset: Dataset, output_dir: Path, _alanmode_calibration
) -> Calibrator:
    calibrator = _alanmode_calibration[1]
    am.write_specal(
        calibrator,
        output_dir / "specal.txt",
        t_load=dataset.acqparams.tload,
        t_load_ns=dataset.acqparams.tcal,
    )

    return am.read_specal(
        output_dir / "specal.txt",
        t_load=dataset.acqparams.tload,
        t_load_ns=dataset.acqparams.tcal,
    )


@pytest.fixture(scope="module")
def legacy_specal(dataset: Dataset) -> Calibrator:
    return am.read_specal(
        dataset.legacy_data_path / "specal.txt",
        t_load=dataset.acqparams.tload,
        t_load_ns=dataset.acqparams.tcal,
    )


@pytest.fixture(scope="module")
def alanmode_calibrated_temps(
    dataset: Dataset, _alanmode_calibration
) -> dict[str, dict[str, np.ndarray]]:
    """Our calibrated temperatures, in the conventions of Alan's calibrated_*.txt.

    Alan's "uncal" column is the approximate temperature Q*tcal + tload (not Q), and
    his calibrated hot-load temperature is corrected for the hot-load cable loss,
    i.e. it is the temperature of the hot load itself, (T - (1-L) T_amb) / L, rather
    than the temperature at the receiver input.
    """
    calobs, calibrator, _ = _alanmode_calibration

    out = {}
    for loadname in am.LOADMAP.values():
        load = calobs.loads[loadname]
        uncal = load.averaged_q * dataset.acqparams.tcal + dataset.acqparams.tload
        cal = calibrator.calibrate_load(load).to_value("K")
        if loadname == "hot_load":
            loss = load.loss
            cal = (cal - (1 - loss) * dataset.calparams.tcold) / loss

        out[loadname] = {
            "freq": load.freqs.to_value("MHz"),
            "uncal": uncal,
            "cal": cal,
        }

    return out


@pytest.fixture(scope="module")
def legacy_calibrated_temps(dataset: Dataset) -> dict[str, np.ndarray]:
    """Alan's calibrated temperatures, read from the legacy C-code outputs."""
    return {
        load: am.read_calibrated_temp(
            dataset.legacy_data_path
            / f"calibrated_{CALIBRATED_TEMP_FILE_KEYS[load]}.txt"
        )
        for load in am.LOADMAP.values()
    }


@pytest.mark.parametrize("load", list(am.LOADMAP.values()))
def test_spectrum_averaging(
    alanmode_averaged_spectra: dict[str, GSData],
    legacy_averaged_spectra: dict[str, GSData],
    load: str,
):
    if not RAW_SPECTRUM_DIR.exists():
        pytest.skip("Raw spectrum data not available, cannot test spectrum averaging.")

    ours = alanmode_averaged_spectra[load]

    np.testing.assert_allclose(legacy_averaged_spectra[load].freqs, ours.freqs)
    np.testing.assert_allclose(
        legacy_averaged_spectra[load].data[20:-20], ours.data[20:-20], atol=1e-6
    )
    # The number of averaged spectra in the file header.
    assert np.max(ours.nsamples) == np.max(legacy_averaged_spectra[load].nsamples)


@pytest.mark.parametrize("legacy_key", [*list(am.LOADMAP.keys()), "lna"])
def test_unmodelled_s11(dataset: Dataset, alanmode_raw_s11s, legacy_key):
    amode_key = "receiver_s11" if legacy_key == "lna" else am.LOADMAP[legacy_key]

    alanfreq, alans11 = am.read_s11_csv(
        dataset.legacy_data_path / f"s11{legacy_key}.csv"
    )
    ourfreq, ours11 = alanmode_raw_s11s
    ours11 = ours11[amode_key]

    mask = (alanfreq >= ourfreq.min()) & (alanfreq <= ourfreq.max())
    np.testing.assert_allclose(alanfreq[mask], ourfreq)
    np.testing.assert_allclose(alans11[mask].real, ours11.real, atol=1e-10)
    np.testing.assert_allclose(alans11[mask].imag, ours11.imag, atol=1e-10)


@pytest.fixture(scope="module")
def legacy_modelled_s11s(dataset: Dataset) -> QTable:
    return am.read_modelled_s11s(dataset.legacy_data_path / "s11_modelled.txt")


def test_modelled_s11(
    alanmode_modelled_s11s: QTable,
    legacy_modelled_s11s: QTable,
):
    alanfreq = legacy_modelled_s11s["freqs"]
    ourfreq = alanmode_modelled_s11s["freqs"]

    # Even though the legacy code ends up using modelled S11s only in the range
    # WFSTART to WFSTOP, the modelled S11s are actually generated across the full range
    # FSTART-FSTOP and written that way, so we need to mask them to compare
    mask = (alanfreq >= ourfreq.min()) & (alanfreq <= ourfreq.max())

    for key in alanmode_modelled_s11s.colnames:
        # Test that all values are good to 2e-5
        np.testing.assert_allclose(
            alanmode_modelled_s11s[key],
            legacy_modelled_s11s[key][mask],
            atol=2e-5,
            rtol=0,
            err_msg=f"Modelled S11 for {key}",
        )

        # Value not near the edges should be even better, at 2e-6
        np.testing.assert_allclose(
            alanmode_modelled_s11s[key][50:-50],
            legacy_modelled_s11s[key][mask][50:-50],
            atol=2e-6,
            rtol=0,
            err_msg=f"Modelled S11 for {key}",
        )


def test_specal(alanmode_specal: Calibrator, legacy_specal: Calibrator):
    np.testing.assert_allclose(legacy_specal.freqs, alanmode_specal.freqs)
    np.testing.assert_allclose(legacy_specal.Tsca, alanmode_specal.Tsca, rtol=3e-6)
    np.testing.assert_allclose(legacy_specal.Toff, alanmode_specal.Toff, atol=4e-5)
    np.testing.assert_allclose(legacy_specal.Tunc, alanmode_specal.Tunc, atol=1.1e-6)
    np.testing.assert_allclose(legacy_specal.Tcos, alanmode_specal.Tcos, atol=2e-5)
    np.testing.assert_allclose(legacy_specal.Tsin, alanmode_specal.Tsin, atol=2.2e-5)


def _matched_calibrated_temps(ours: dict, alan: np.ndarray) -> np.ndarray:
    """Cut Alan's calibrated temperatures to the frequencies we calibrate."""
    # Alan writes the calibrated temperatures on fstart-fstop, while we only calibrate
    # within wfstart-wfstop. Allow a tiny tolerance for the file's precision.
    mask = (alan["freq"] >= ours["freq"].min() - 1e-6) & (
        alan["freq"] <= ours["freq"].max() + 1e-6
    )
    alan = alan[mask]
    np.testing.assert_allclose(ours["freq"], alan["freq"], atol=1e-9, rtol=0)
    return alan


@pytest.mark.parametrize("key", am.LOADMAP.values())
def test_calibrated_temps(
    dataset: Dataset,
    alanmode_calibrated_temps: dict[str, dict[str, np.ndarray]],
    legacy_calibrated_temps: dict[str, np.ndarray],
    key: str,
):
    ours = alanmode_calibrated_temps[key]
    alan = _matched_calibrated_temps(ours, legacy_calibrated_temps[key])

    np.testing.assert_allclose(ours["uncal"], alan["uncal"], atol=1e-9, rtol=0)
    np.testing.assert_allclose(
        ours["cal"], alan["cal"], atol=dataset.calibrated_temp_atol[key], rtol=0
    )


@pytest.mark.xfail(
    strict=True,
    reason=(
        "Calibrated open/short temperatures differ from Alan's C code by up to "
        "~1.5 mK (2022_316, largest at the 50 MHz edge) and ~0.1-0.2 mK (2023_210), "
        "much more than the <0.1 mK agreement of the ambient and hot loads. The cause "
        "is not yet understood (issue #311)."
    ),
)
@pytest.mark.parametrize("key", ["open", "short"])
def test_calibrated_temps_open_short_tight(
    alanmode_calibrated_temps: dict[str, dict[str, np.ndarray]],
    legacy_calibrated_temps: dict[str, np.ndarray],
    key: str,
):
    ours = alanmode_calibrated_temps[key]
    alan = _matched_calibrated_temps(ours, legacy_calibrated_temps[key])

    # The same precision as the ambient load attains.
    np.testing.assert_allclose(ours["cal"], alan["cal"], atol=5e-5, rtol=0)


@pytest.mark.xfail(
    strict=True,
    reason=(
        "On hold pending a hardware check: CalibrationObservation."
        "from_edges3_caldef passes cable_loss_percent and cable_dielectric_percent "
        "as percent Quantities, which are converted to fractions twice (lossf 0.99085 "
        "instead of Alan's 0.085), and defaults the match resistance to 49.962 Ohm "
        "where alanmode and Alan's C code use 49.8 Ohm. Both are under review; fix "
        "pending (result-changing)."
    ),
)
def test_receiver_s11_matches_from_edges3_caldef(monkeypatch):
    """Cross-pipeline check: alanmode and edges.cal give the same receiver S11.

    The spectra (.acq files) for this day are not in the repo, so we cannot build the
    full CalibrationObservation. Instead we intercept ``_from_caldef`` to compute only
    the raw receiver reflection coefficient, exactly as ``_from_caldef`` does it, from
    the receiver options that ``from_edges3_caldef`` sets by default.
    """
    dataset = DATASETS["2022_316"]
    s11freq, raws11s = dataset.defparams.get_raw_s11s()

    def _raw_receiver_only(cls, caldef, *, receiver_kwargs=None, **kwargs):
        receiver_kwargs = dict(receiver_kwargs or {})
        receiver_kwargs.pop("model_params", None)
        return sp.get_gamma_receiver_from_filespec(caldef, **receiver_kwargs)

    monkeypatch.setattr(
        CalibrationObservation, "_from_caldef", classmethod(_raw_receiver_only)
    )
    raw_receiver = CalibrationObservation.from_edges3_caldef(
        dataset.defparams.get_caldef()
    )

    np.testing.assert_allclose(
        raw_receiver.freqs.to_value("MHz"), s11freq.to_value("MHz"), rtol=1e-12
    )
    np.testing.assert_allclose(
        raw_receiver.reflection_coefficient,
        raws11s["receiver_s11"],
        atol=1e-10,
        rtol=0,
    )
