gha_bin_size: 0.5
sun_el_max: 90
moon_el_max: 90
ambient_humidity_max: 40
min_receiver_temp: 0
max_receiver_temp: 100
rms_filter_file: null
do_total_power_filter: false
xrfi_pipe:
  xrfi_poly:
    n_signal: 4
    n_resid: -1
    threshold: 10
    max_iter: 20
    increase_order: true
    decrement_threshold: 1
    min_threshold: 3
