band: mid
calfile: ~/data4/temporary_calibration_2019_11.h5
s11_path: ':daily'
balun_correction: true
antenna_correction: ':bladebox_perf.txt'
ground_correction: ':ground_loss.txt'
ignore_s11_files:
  - '2020_06'
  - '2020_070'
  - '2020_071'
  - '2020_072'
