name: Check Changelog
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main
      - develop

jobs:
  build:
    name: Check Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Changelog check
        uses: Zomzog/changelog-checker@v1.1.0
        with:
          fileName: CHANGELOG.md
          noChangelogLabel: no changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
